import pandas as pd

df1 = pd.read_excel('Civil society.xlsx')
df2 = pd.read_excel('Domestic Violence.xlsx')
df3 = pd.read_excel('Drugs.xlsx')
df4 = pd.read_excel('Education.xlsx')
df5 = pd.read_excel('Government.xlsx')
df6 = pd.read_excel('GT-Extortion.xlsx')
df7 = pd.read_excel('GT-Kidnapping.xlsx')
df8 = pd.read_excel('GT-Killing.xlsx')
df9 = pd.read_excel('GT-Pandillas.xlsx')
df10 = pd.read_excel('HN-Extortion.xlsx')
df11 = pd.read_excel('HN-Killing.xlsx')
df12 = pd.readexcel('HN-Pandillas.xlsx')
df13 = pd.read_excel('Justice and Security.xlsx')
df14 = pd.read_excel('Migration.xlsx')
df15 = pd.read_excel('Public transportation.xlsx')
df16 = pd.read_excel('SV-Extortion.xlsx')
df17 = pd.read_excel('SV-Killing.xlsx')
df18 = pd.read_excel('SV-Pandillas.xlsx')
df19 = pd.read_excel('Unemployment.xlsx')
df20 = pd.read_excel('Weapons.xlsx')
